@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.sirvincelot24.mantle_reforged.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
