@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.sirvincelot24.mantle_reforged.registration.deferred;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
