@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.sirvincelot24.mantle_reforged.registration.object;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
