@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.sirvincelot24.mantle_reforged.recipe.ingredient;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
